[theme]
base="dark"  # or "dark"
primaryColor="#e6f6ff"       # buttons, highlights
backgroundColor="#e6f6ff"    # main background
secondaryBackgroundColor="#58a0c8"  # sidebar, widgets
textColor="#113f67"          # normal text
font="sans serif"            # or "serif", "monospace"
